### ISSUE TITLE
Add for amazon video watch history

### ISSUE THREAD

**Issue by willhubs** [igorlogius/automate-click#12]
Amazon prime TV and Movie watch history:
https://www.amazon.com/gp/video/settings/watch-history/ref=dv_auth_ret?

Not sure if the selector is the same for everyone, but this worked on mine.
[
    {
        "activ": true,
        "annotation": "",
        "url_regex": "^https:\\/\\/www.amazon\\.com.*",
        "code": "._17wtYU._17wtYU ._3zBFNK ._1x0tR0 ._2PqNPo",
        "delay": 1000,
        "repeat": 2000
    }
]

**Comment by igorlogius** [comment]
No reply for a considerable amount of time, ... so closing this for now.
