### ISSUE TITLE
[Feature Request]  add option to make the repeat delay (random within bounds)  

### ISSUE THREAD

**Issue by pexxpeppa** [igorlogius/automate-click#13]
It would be nice to add an option to delay and repeat action in random time intervals. Let's say I want to click on something in this random time interval (5000 to 15000). So each auto click is something random  between 5000 and 15000ms. Thank you!

**Comment by igorlogius** [comment]
@pexxpeppa  
Sounds like a nice idea, i just have to think how to best add this a bit without cluttering the UI.

**Comment by igorlogius** [comment]
My current prevered solution would be to replace the repeat action and insted add a min and max repeat range, if both values are equal, that would define a single repeat value, if max > min  => pick a random value in between them.

I dont really want to add to many switches ... /checkboxes  and that would work, but ... 
i fear that the min-max repeat and ranodm behaviour is not exactly easy to understand ... argh ... i have to think about this more sorry.

**Comment by pexxpeppa** [comment]
> 
> 
> My current prevered solution would be to replace the repeat action and insted add a min and max repeat range, if both values are equal, that would define a single repeat value, if max > min => pick a random value in between them.
> 
> I dont really want to add to many switches ... /checkboxes and that would work, but ... i fear that the min-max repeat and ranodm behaviour is not exactly easy to understand ... argh ... i have to think about this more sorry.

Yeah, actually I do understand, but I'm afraid I wouldn't if you didn't explain it first :-)

**Comment by pexxpeppa** [comment]
> My current prevered solution would be to replace the repeat action and insted add a min and max repeat range, if both values are equal, that would define a single repeat value, if max > min => pick a random value in between them.
> 
> I dont really want to add to many switches ... /checkboxes and that would work, but ... i fear that the min-max repeat and ranodm behaviour is not exactly easy to understand ... argh ... i have to think about this more sorry.

Any updates on this?:-)

**Comment by igorlogius** [comment]
I will have some time to start working on a "good" solution  when the holidays (christmas) are starting.
Sorry for the delay. But i think you can expect the feature at the latest at the beginning of the new year.

**Comment by pexxpeppa** [comment]
> I will have some time to start working on a "good" solution when the holidays (christmas) are starting. Sorry for the delay. But i think you can expect the feature at the latest at the beginning of the new year.

Good to hear! Thank you very much!

**Comment by igorlogius** [comment]
@pexxpeppa : 
So i opted to be a lazy person and only added a "variance" number input field. (Random Repeat Variance)
As the name implies it allows to add a "variance" to the repeat delay  so the actuall delay will be randomly selected as a value 
between [Repdat Delay] - [RRV]  and [RepeatDelay] + [RRV]. 

Hope that is good enough for your usecase.  

I am not yet ready to make this an offical AMO release, but 
you can try out the new Version 1.5.8 beforehand like this:   

1. download the latest release zip 
2. open a new tab with this url:  `about:debugging#/runtime/this-firefox`
3. Click on the  "Load Temporary Add-on ..." Button and choose the downloaded zip file.
Note: 
This installation will not persist between browser restarts 

I'll leave this issue open for now, and if you like you can come back with any feedback you might have.

**Comment by igorlogius** [comment]
Released as part of  version 1.6.9
