### ISSUE TITLE
add a description column

### ISSUE THREAD

**Issue by yazmed** [igorlogius/automate-click#2]
can you consider adding a description column to distinguish between clicks on a particular website.
your work is apreciated.

**Comment by igorlogius** [comment]
The idea is good.

The Preference page which is currently used for adding entries is rather limited in horizontal space.
And i was already considering to use a seperate configuration page or a differnt location  (sidebar / toolbar dropdown)
for managing the configuration. 

I am just not sure which would be the better choice.
