### ISSUE TITLE
Could autoclicking any link be realized?

### ISSUE THREAD

**Issue by minshifu** [igorlogius/automate-click#21]
Thank you for your excellent addon.

Could you pls enable autoclicking any link on webpages?

I miss one addon very much that could function just like this many years ago and has long beeb defunct.

Such an addon can save lots of effort especially when someone's work requires a lot of browsing everyday.
                  Best regards!

**Comment by igorlogius** [comment]
Any link? You mean link randomly clicking on an item?

**Comment by igorlogius** [comment]
Sounds more like a job for a userscript manager, like greasymonkey or violentmonkey 

You can use a code snippet like this, to get started: 

```
// ==UserScript==
// @name        RandomNavi
// @namespace   Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @description 7/27/2022, 4:05:36 PM
// ==/UserScript==

setTimeout(function(){
    const anchors = document.querySelectorAll('a[href^="http"]');
    if(anchors.length < 0){ 
      if(history.length > 1){
        history.back();   // go back to the previous page, if this one does not have any links 
      }
      return; 
    }  // go back to previous page 
    const random_click_target = anchors[Math.floor(Math.random()*anchors.length)];                                               
    random_click_target.click();
  }, 5000  // wait 5000 milliseconds aka. 5 Seconds for website to "settle"
); 
```

This will wait 5 seconds, then select random anchor with a href to a "http" target and click on it. 
If there is no link, it will navigate one step back and repeat the process.

It has the following 2 Issues

1. no hisotry + no link => termintate
2. it might click the same links twice 

Hope it helps.

**Comment by minshifu** [comment]
> 

Thank you so much! Is this how to use it as shown by the picture below? I copied your script into Violentmonkey and saved it. But it did not seem to be working. Or did I get it wrong? 
![图片](https://user-images.githubusercontent.com/5119952/181545771-d2d3d12f-b348-4fb0-966a-26c5960fd1d8.png)

**Comment by igorlogius** [comment]
@minshifu  Looks fine, as far as i can see. I would say, that it should work, when you open a new tab of a valid website.

**Comment by minshifu** [comment]
> @minshifu Looks fine, as far as i can see. I would say, that it should work, when you open a new tab of a valid website.

Thanks. Tried it again and it does work. But is it possible to have an addon to autoclick and open the link I choose to hover over instead of randomly opening one? Best regards!

**Comment by igorlogius** [comment]
@minshifu  This might be what you want. 

```
// ==UserScript==
// @name        HoverNavi
// @namespace   Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @description -
// ==/UserScript==

document.addEventListener('mouseover', (event) => {
    if(event.target.nodeName === 'A'){
        event.target.click();
    }
});

```

**Comment by minshifu** [comment]
> @minshifu This might be what you want.
> 
> ```
> // ==UserScript==
> // @name        HoverNavi
> // @namespace   Scripts
> // @match       *://*/*
> // @grant       none
> // @version     1.0
> // @author      -
> // @description -
> // ==/UserScript==
> 
> document.addEventListener('mouseover', (event) => {
>     if(event.target.nodeName === 'A'){
>         event.target.click();
>     }
> });
> ```

Thank you so much. I've tried it. Could Google search results page be supported? Also could page popup be allowed in general? Currently, confirmation is required on nearly every page when a link is autoclicked and a page behind that link needs to pop up.

**Comment by igorlogius** [comment]
> Thank you so much.

You are welcome. 

> Could Google search results page be supported?

I assume you want want to click on Buttons as well as on links? 
In that case you will need to add more `if` statements to detect the differnt types of elements.

```
document.addEventListener('mouseover', (event) => {
   const node = event.target;
   const nodeName = node.nodeName.toLowerCase();
    if (    ( nodeName === 'a' )
         || ( nodeName === 'button' )
         || ( nodeName === 'input'  && typeof event.target.type === 'string' && event.target.type === 'button' )
    ) {
        node.click();
    }
});
```

Please note, that some "links" are just other html elements with "onclick" handlers.  
In that case this method of navigation will not work. 


> Also could page popup be allowed in general? Currently, confirmation is required on nearly every page when a link is autoclicked and a page behind that link needs to pop up.

Sorry, but i dont quite understand what you mean with this.

**Comment by minshifu** [comment]
> > Thank you so much.
> 
> You are welcome.
> 
> > Could Google search results page be supported?
> 
> I assume you want to click on Buttons as well as on links? In that case you will need to add more `if` conditions to detect the differnt elements.
> 
I am referring to the links on Google search results pages as shown by the picture below. Now the script does not seem to be able to work on them.
![图片](https://user-images.githubusercontent.com/5119952/182613253-cf313339-a513-4204-941c-ff36777854a9.png)

**Comment by minshifu** [comment]
> > Also could page popup be allowed in general? Currently, confirmation is required on nearly every page when a link is autoclicked and a page behind that link needs to pop up.
> 
> Sorry, but i dont understand what you mean.

As shown by the picture, popup confirmation is needed on almost every page when the script is working.Is there a way to avoid this? 

![图片](https://user-images.githubusercontent.com/5119952/182619707-e92e6a46-428d-434b-a389-0f0449fc321b.png)

**Comment by igorlogius** [comment]
Those green "HTML Elements" are exactly what i meant with "not actual links". They are  cite elements which have been given a javascript onclick handler ... To make the script handle those i suppose it would be best to limit this "special" handling to be site specific, to prevent invalid use on other sites. 

So you could do someting like this: 
```
document.addEventListener('mouseover', (event) => {
   const node = event.target;
   const nodeName = node.nodeName.toLowerCase();
    if ( window.location.href.startsWith("https://www.google.com/search" ){
           if (    (  nodeName === 'cite' ) // anchor
                    node.click();
                    return; 
           }  
    }
    if (    (  nodeName === 'a' ) // anchor
         || (  nodeName === 'button' ) // button 
         || (  nodeName === 'input'  && typeof node.type === 'string' && ['button','submit'].includes(node.type.toLowerCase()) )
    ) {
        node.click();
    }
});
```

Regarding the popup notifications ... i think there are a couple of setting regarding popup handling ... and also some addons. Not sure which would be the most useful in your case. Guess you have to experiment and find out. 

Hope this still helps you out a little. 
Good luck.

**Comment by minshifu** [comment]
> Those green "HTML Elements" are exactly what i meant with "not actual links". They are cite elements which have been given a javascript onclick handler ... To make the script handle those i suppose it would be best to limit this "special" handling to be site specific, to prevent invalid use on other sites.
> 
> So you could do someting like this:
> 
> ```
> document.addEventListener('mouseover', (event) => {
>    const node = event.target;
>    const nodeName = node.nodeName.toLowerCase();
>     if ( window.location.href.startsWith("https://www.google.com/search" ) ){
>            if (    (  nodeName === 'cite' ) // anchor
>                     node.click();
>                     return; 
>            }  
>     }
>     if (    (  nodeName === 'a' ) // anchor
>          || (  nodeName === 'button' ) // button 
>          || (  nodeName === 'input'  && typeof node.type === 'string' && ['button','submit'].includes(node.type.toLowerCase()) )
>     ) {
>         node.click();
>     }
> });
> ```
> 
> Regarding the popup notifications ... i think there are fiefox settings (`about:config`) regarding popup handling ... and also some addons. Not sure which would be the most useful in your case. Guess you have to experiment and find out.
> 
> Hope this still helps you out a little. Good luck.

Sorry to bother you again. But there seems to be an error.

![图片](https://user-images.githubusercontent.com/5119952/183230480-0d28868c-5616-43b6-8429-362ab1dce4b6.png)

**Comment by igorlogius** [comment]
Still not sure what it is you are trying todo exactly, but if you are unable to fix a realtively simple syntax error like this, i hope you know what you are trying todo here. 

Anyways, here is the complete fixed and tested code.
If you need further help, please go ask on StackOverflow other another forum, since this conversation has nothing todo with this addon anymore. 

```
// ==UserScript==
// @name        HoverNavi2
// @namespace   Scripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      -
// @description -
// ==/UserScript==

document.addEventListener('mouseover', (event) => {
   var node = event.target;
   var  nodeName = node.nodeName.toLowerCase();
    if ( window.location.href.startsWith("https://www.google.com/search" ) ){
           if ( nodeName === 'cite' ) {
                    node.click();
                    return; 
           }  
    }
    if (    (  nodeName === 'a' ) // anchor
         || (  nodeName === 'button' ) // button 
         || (  nodeName === 'input'  && typeof node.type === 'string' && ['button','submit'].includes(node.type.toLowerCase()) )
    ) {
        node.click();
    }
});
```

Bye.

**Comment by minshifu** [comment]
> Still not sure what it is you are trying todo exactly, but if you are unable to fix a realtively simple syntax error like this, i hope you know what you are trying todo here.
> 
> Anyways, here is the complete fixed and tested code.
> 
> ```
> // ==UserScript==
> // @name        HoverNavi2
> // @namespace   Scripts
> // @match       *://*/*
> // @grant       none
> // @version     1.0
> // @author      -
> // @description -
> // ==/UserScript==
> 
> document.addEventListener('mouseover', (event) => {
>    var node = event.target;
>    var  nodeName = node.nodeName.toLowerCase();
>     if ( window.location.href.startsWith("https://www.google.com/search" ) ){
>            if ( nodeName === 'cite' ) {
>                     node.click();
>                     return; 
>            }  
>     }
>     if (    (  nodeName === 'a' ) // anchor
>          || (  nodeName === 'button' ) // button 
>          || (  nodeName === 'input'  && typeof node.type === 'string' && ['button','submit'].includes(node.type.toLowerCase()) )
>     ) {
>         node.click();
>     }
> });
> ```
> 
> If you need further help, maybe go ask on StackOverflow or another user forum, since this conversation has nothing todo with this addon anymore. Good luck.

Got it! Thank you so much. Have a good day!
