### ISSUE TITLE
Clicking on page absolute coordinates

### ISSUE THREAD

**Issue by heltua** [igorlogius/automate-click#22]
Recently one site I had automated with automate-click was updated and now there is a button you have click in time intervals. The problem is, the button has dynamic, randomly generated css class now, so there is no option to create a repeating rule for the click. So I thought, maybe it would be really cool to make the clicker able to learn and click on specific coordinates instead. The button is always on the same spot, so basically once you'd show where to click, and next time the clicker clicks on the specific spot (button) - no classes needed. Checked the FF addon catalog, didn't find anything like that (clicking on coords). That would be the real deal.

**Comment by igorlogius** [comment]
Hi @heltua,

thanks for taking the time to share your idea. 
I can see how this might be useful but i think there might be issues with changing clientsite viewport/window sizes. 

But i'll look into this and see if there is a way to make this a viable option.

**Comment by igorlogius** [comment]
Note: 

The worst part of this ,isnt the clicking on coordinates, but changing the UI ... in a way that incorperates the input of the relative - offsets. 

The simples but very ugly solution would be to just add a checkbox and 2 addional number inputs per line where the user can input a viewport-top (vh)  percentage and a viewport-left (vw) percentage. 

Definetly gonna be hidden per default. 

A better solution would be to toggle to switch the css selector with the coordinates ... but that requires even more UI stuff, so ... something for later maybe. (aka. read: never)

**Comment by heltua** [comment]
> The simples but very ugly solution would be to just add a checkbox and 2 addional number inputs per line where the user can input a viewport-top (vh) percentage and a viewport-left (vw) percentage.

Basically that's what I imagined.

**Comment by igorlogius** [comment]
@heltua  
Find the abolute postions of the element you want to click via 

```
X := element.offsetLeft
Y := element.offsetTop 
```

And place these values into the `X-Click Position` and `Y-Click Position` (hidden) columns.  
Not sure how useful this is gone be, but maybe that is enough to cover your usecase.

If not, feel free to let me know about any remaining issues. 
I wont promise any solutions, but i'll definitely look and think about if there is anything i can do. 

Later, maybe.

**Comment by orcusbeat** [comment]
@igorlogius I am very new to web development in general, could you please explain further how to get those values? 

Sorry for such a stupid question

**Comment by igorlogius** [comment]
@orcusbeat  

It's fine, we all start somewhere. Just dont get to used to people spoon feeding you. There is a lot of documentation on the net. I'd personally recommend https://developer.mozilla.org/en-US/docs/Web/JavaScript

There are a couple of way to get the position values. Here is one, that i think should work: 

1. Open the Development Console (F12 or Ctrl+Shift+i )
3. Goto the "Console"  tab (if that is not active)
4. Paste `onmousemove = function(e){console.log("mouse location:", e.clientX, e.clientY)}`  into the prompt area and hit enter

Now when you move the mouse over the page, the Console should print the X and Y positions where the mouse is. 

Hope it helps. 

PS: 
Positioning are window, screen size and scale depended, hope this approch works out for you. 
There was a reason i did not initally include it. :-)
