### ISSUE TITLE
Quicker rule creation from active tab (via context menu) 

### ISSUE THREAD

**Issue by khabib227** [igorlogius/automate-click#23]
First, thanks, nice plugin! Please add a context menu entry, so if clicked the plugin automatically make a new rule using the current URL (main domain ex. "https://github.com/") and with the CSS Path under the cursor, and show you a simple popup that show the data to confirm, and in this popup you also can edit the rule, including a slider to choose the URL level, for instance if is activated on subdomain, if only in one folder, or a specific folder, etc, you just slide to set the URL or can edit manualy. And add a setting to set default Initial Delay. Thanks

**Comment by khabib227** [comment]
Also please think in add a new action, "view image", so the user can use this action instead of the click action, this can be very useful to skip webpages in photo sites, that show a image in a "frame" into a webpage, so you can right click this non clickable image, click on context menu entry, and the plugin can use the CSS Path of this image to create the rule.

**Comment by khabib227** [comment]
An example of an site that this "view image" action can be useful: "pixhost.to", in this case the image is clickable, but do not open the original image, just add a zoom effect keeping you into a webpage,

**Comment by igorlogius** [comment]
@khabib227  
>First, thanks, nice plugin! 
no problem

> Please add a context menu entry, so if clicked the plugin automatically make a new rule using the current URL (main domain ex. "https://github.com/") and with the CSS Path under the cursor, and show you a simple popup that show the data to confirm, and in this popup you also can edit the rule, including a slider to choose the URL level, for instance if is activated on subdomain, if only in one folder, or a specific folder, etc, you just slide to set the URL or can edit manualy. And add a setting to set default Initial Delay.

Argh, so much,  ...   i can see that having a way to quickly create a rule for the current page, without having to switch into another context is useful, i might have to make a simple prototype before adding any advanced options. I am really not good with UI stuff, so no promises.   

> Also please think in add a new action, "view image", so the user can use this action instead of the click action, this can be very useful to skip webpages in photo sites, that show a image in a "frame" into a webpage, so you can right click this non clickable image, click on context menu entry, and the plugin can use the CSS Path of this image to create the rule.  

Well, technical ... i could add differnt actions, like (focus, remove, right click, ... ) but i am not sure if that is really what you need/want/mean.  Maybe you can create a 2nd issue and explain exactly what it is you are trying todo?
With a Steps by Step description (+example page)  so i can  follow and reproduce your usecase.

**Comment by khabib227** [comment]
All right, about the slider to set the URL level, it was just a suggestion, but is not essential, if the popup has a editable field to edit the URL, it is sufficient. Thanks the attention.

**Comment by khabib227** [comment]
You can also add two context menu entries, one to add a new rule, and another to just add a URL to a old rule, as explained here:

https://github.com/igorlogius/automate-click/issues/24#issuecomment-1235780129

**Comment by igorlogius** [comment]
new Version 1.12.7 

When clicking the toolbar button now the url regex gets prefilled with something hopefully useful ... might still need some tweaking ... but there is not much i can to about that.  At least it should make things a little easier. 

>  You can also add two context menu entries, one to add a new rule, and another to just add a URL to a old rule, as explained here:

No, sadly, i can not think of a good way to add such a feature at the current time. 

PS: 
Please try to keep feature request (even similar ones) seperated. Writing everything you think of into one issue, makes things harder for me to process and in turn lessens the likelyhood for me to actually work on it. 
Sorry for preaching, but its a small thing, that helps a lot.

**Comment by khabib227** [comment]
@igorlogius, thanks, if possible an day, if you have a time, think in add a context menu that can extract also the CSS under the cursor,

**Comment by igorlogius** [comment]
@khabib227  
I can see how this feature would make  AC much more usable for a lot of people, but i simply fear that if i implement something basic, that it will just not fullfill peoples general expections and fail on many occassions. 
So for the time being (until i really feal motivated) i'll rather refer people to using the firefox's built-in page inspector. (ref. https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/open_the_inspector/index.html ) 

If you like, you can open another issue (with just the request for a selector)  for this.
I can label it with a "help wanted"  and if anyone wants to make a pull request, i'll take a look at it, but i wont be spending time on this feature myself, at least at the moment.

**Comment by khabib227** [comment]
All right, thanks!
