### ISSUE TITLE
Add "View Image" action

### ISSUE THREAD

**Issue by khabib227** [igorlogius/automate-click#24]
Has many services on internet today to host images, you know, but many of this services show the image into a webpage and don't show the original image directly, or give you a option to show directly, so you need right click the image in this page and go to "View Image" in context menu from Firefox for instance, this action open the original image without any webpage or htmls. In some of this services the image IS NOT clickable, in others if you click this don't open the original image, but, just enable a zoom effect. I want to suggest add to plugin the "View Image" action. Example:

https://pixhost.to/show/84/179463132_2aed6ae8-5628-4b5c-b8d8-b4130d02747d.jpg

I can add a rule with this CSS Path:

html body div#web div#content-container div#content div#show div.image img#image.image-img

And instead of use the default "Click Action" I can use the new "View Image Action" so the plugin don't simulate a click over this image, but simulate the "View Image Action" using this CSS Patch. This is very useful, is more or less like the plugin "Largest image by mihkeltt" but much better, automatic and more effective, because the "Largest image" plugin is very good but sometimes fail to find the largest image. Thanks!

**Comment by khabib227** [comment]
You can even add another action with the "Largest image by mihkeltt"  algorithm as a backup, so if some service someway block the "View Image", the user can use this algorithm as alternative.

**Comment by khabib227** [comment]
Also another advantage of the "algorithm" alternative, is that you can create just one rule, for several sites, using just one regular expression, for multiple URLs, and put the "algorithm" as the automatic action, so using the "algorithm" you don't need the CSS for each site. If possible, please, add this two actions, "View Image" and the "Largest image by mihkeltt algorithm". In another post I suggested the context menu entry to add a rule easily, on the popup you can also make possible the user add a new site (URL) to a already created rule. For instance I have a rule using the "Largest image algorithm", so I can use the context menu just to add a new URL to this rule, avoiding create a new one.

**Comment by khabib227** [comment]
Sorry if I used so much words, is just a suggestion to you think about, I think that your plugin is very good and I think that with this two actions your plugin would be the best plugin to skip intermediate webpages of all time. Thanks!

**Comment by igorlogius** [comment]
This also seems to be a bit out-of-scope, for what this addon tries to provide. 
At the current time I dont intent to add more addional actions. 

For the time being i would suggest you also take a look at userscripts for your usecase and maybe one of these addons can help you out a little

- https://addons.mozilla.org/en-US/firefox/addon/fastforwardteam/
- https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/

Sorry.

**Comment by khabib227** [comment]
@igorlogius, "Skip Redirect" is another thing, and "Fast Forward" is not easy to make custom scripts, please add at least the "view image" action, just it to me can be sufficient!

**Comment by igorlogius** [comment]
@khabib227  Sorry, i dont see this feature as something AC should provide. 

But it does sound like a good job for a custom userscript. 
Should not even be very difficult to make, since everything you seemed to want is to open a image source of css match when visiting a certain urls.

I could maybe give you a basic greasymonkey script template where you only need to add the url regex's and css selectors, if you are interested.

**Comment by khabib227** [comment]
I accept the script, but need a "delay" setting, because many of this photo hosts sometimes has a "click to continue page" so I can click on continue link with AC and put a delay on the userscript.

**Comment by khabib227** [comment]
If possible please write a script that I can put the url regex, a initial delay, a field to put the css selectors "to click", another delay, and a field to put the css selectors to extract the images, so I can use just the script to click and to extract images. :D

**Comment by igorlogius** [comment]
Here you go: 

```
// ==UserScript==
// @name        follow source
// @namespace   Userscripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      igorlogius
// @description 9/6/2022, 8:11:26 AM
// ==/UserScript==
  
// Variables
const current_url = window.location.href; 
const rules = new Map();
let re; 


// !!! Add your own Rules here  -- format: rules.set('regex', {delay, selector }]);

rules.set('^https://www\.facebook\.com', {delay: 3000, selector: '.fb_logo' });
//rules.set('^https://www\.facebook\.com', {delay: 3000, selector: '.fb_logo' });
//rules.set('^https://www\.facebook\.com', {delay: 3000, selector: '.fb_logo' });
//rules.set('^https://www\.facebook\.com', {delay: 3000, selector: '.fb_logo' });
// 

// -- MAIN -- 
for(const [k,v] of rules) {
  re = new RegExp(k); 
  if(re.test(current_url)){
    console.debug('[DEBUG] match', k, current_url);
    setTimeout( () => {
      console.debug('[DEBUG] executing delayed action', v.selector)
      const el = document.querySelector(v.selector); 
      if(typeof el.src === 'string'){
         document.location = el.src; 
      }
    }, v.delay); 
  }
}
```

Use a userscript manager, like greasy-, violent-, or tampermonkey and import/paste the script. 
For a quick test, you can visit https://www.facebook.com and after 3 seconds, the facebook logo should be navigated to. 

To add further sites, you just have to add a rule line like this: 

`rules.set('^https://www\.facebook\.com', {delay: 3000, selector: '.fb_logo' });`

with the fitting value. 

regex: string ( a javascript valid url regex, see. https://regex101.com )
delay: integer  (delay in milliseconds, 1000ms := 1s )
selector:  string   ( a valid css selection query )

**Comment by khabib227** [comment]
thanks, but don't work I tried for instance for this site:

https://pixhost.to/show/84/179463132_2aed6ae8-5628-4b5c-b8d8-b4130d02747d.jpg

this:
rules.set('^https://www\.pixhost\.to', {click_delay: 500, click_selector: '', image_delay: 2000, image_selector: '.image-img' });

I also tried:

.image 

#image

I'm doing something wrong?

**Comment by khabib227** [comment]
The click_selector was empty because this site don't need click, but in other tests I tried just the click function and don't worked also

**Comment by igorlogius** [comment]
@khabib227  There is literally nothing in your last statement which would help my idnetify what your issue is. 

If you need further help, please provide a step by step description of what you are doing, followed by the description of what you expect the result to be and the actual result you currently get. 

To be honest, this is getting a little tedious, so please make sure that your next reply at least contains some useful information.

**Comment by khabib227** [comment]
For instance this site:

https://pixhost.to/show/84/179463132_2aed6ae8-5628-4b5c-b8d8-b4130d02747d.jpg

I used your script as below, but don't worked, tested on Tamper and Violent Monkies, on Imagebam service also click and image extraction don't worked:

// ==UserScript==
// @name        follow source
// @namespace   Userscripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      igorlogius
// @description 9/6/2022, 8:11:26 AM
// ==/UserScript==

// Variables
const current_url = window.location.href;
const rules = new Map();
let re;


// !!! Add your own Rules here  -- format: rules.set('regex', {click_delay, click_selector, image_delay, image_selector }]);

rules.set('^https://www\.imagebam\.com', {click_delay: 2000, click_selector: '#continue', image_delay: 2000, image_selector: '.main-image' });

rules.set('^https://www\.pixhost\.to', {click_delay: 2000, click_selector: '', image_delay: 2000, image_selector: '.image-img' });

// -- MAIN --
for(const [k,v] of rules) {
  re = new RegExp(k);
  if(re.test(current_url)){
    console.debug('[DEBUG] match', k, current_url);

    setTimeout( () => {
      console.debug('[DEBUG] click action', v.click_selector)
      const click_el = document.querySelector(v.click_selector);

      if(typeof click_el.click === 'function') {
        setTimeout( () => {
          console.debug('[DEBUG] image action', v.image_selector)
          const image_el = document.querySelector(v.image_selector);
          if(typeof image_el.src === 'string'){
             window.location = image_el.src;
          }
        }, v.image_delay);
      }

    }, v.click_delay);
  }
}

**Comment by grant** [comment]
Please don't @ me unless you're looking for my review. Thanks!

**Comment by khabib227** [comment]
You can try Imagebam here:

https://www.imagebam.com/view/GA4YW

But Imagebam don't show the "continue link webpage" every time, just sometimes,

**Comment by khabib227** [comment]
And just to be clear, I used:

@match *://*/*

**Comment by khabib227** [comment]
Github deleted my asterisks,

**Comment by igorlogius** [comment]
@khabib227 

You should be more careful with making posts, maybe think a little longer on what you want to write ... 
you kind of  spamming me with notifications ATM.  

Regarding your two rules: 
In both cases there are issues with the `click_selector`

1. For  '^https://www\.pixhost\.to'  you left the on click selector empty , which is ATM not an option , you have to define someting that can be clicked onrotherwise the script will not continue

2. On  https://www.imagebam.com/view/GA4YW  there is no element which matches  the  '#continue' selector and the script fails too. 

I can patch the script a little more to allow the contineu to be optional if you want?

**Comment by igorlogius** [comment]
> Github deleted my asterisks,

You know you can edit your posts and comments right?

**Comment by igorlogius** [comment]
This snippet is modified to allow you to execute how many actions you want, just remember that 
all actions are queued at the same time, you need to set the delays appropiately for actions to happen in an order you want. 

```
// ==UserScript==
// @name        MultiActionScript v1
// @namespace   Userscripts
// @match       *://*/*
// @grant       none
// @version     1.0
// @author      igorlogius
// @description 9/6/2022, 8:11:26 AM
// ==/UserScript==
  
// Variables 
const current_url = window.location.href; 
const rules = new Map();
let re; 


// -- Begin Rules --

// !!! Add your rules here !!!  

// Example, clicking on a button and then navigating to the source of an image
rules.set('^https://www\.facebook\.com', 
  [
    {action: 'click', delay: 2000, selector: 'button[data-cookiebanner="accept_only_essential_button"]'},
    {action: 'image', delay: 3000, selector: '.fb_logo'}
  ]
);

// Example Rule, just clicking on a link
rules.set('^https://example\.net', 
  [
    {action: 'click', delay: 2000, selector: 'body > div:nth-child(1) > p:nth-child(3) > a:nth-child(1)' }
  ]
);



// -- End Rules --


// actions functions, can be easily extended

function clickAction(el) {
  if(typeof el.click === 'function') {  
            el.click();
  }
}

function imageAction(el){
  if(typeof el.src === 'string'){
    window.location = el.src; 
  }
}

// -- MAIN LOOP-- 
for(const [key, values] of rules) {
  console.log(key, current_url);
  re = new RegExp(key); 
  if(re.test(current_url)){
    console.debug('[DEBUG] match', key, current_url);
    for(const v of values){ 
      if(typeof v.delay === 'number' && v.delay > 0) {
        setTimeout(() => {  
          try {
            const el = document.querySelector(v.selector); 
            if(el && typeof v.action === 'string') {
              switch(v.action.toLowerCase()){
                case 'click': 
                  clickAction(el);
                  break;
                case 'image': 
                  imageAction(el);
                  break;
              }
            }
          }catch(e) {
            console.error(e);
          }
        }, v.delay);
      }
    } 
  }
}
```

Hope it helps.

**Comment by khabib227** [comment]
Sorry something, the posts, notifications, etc, and big thanks now the script is working perfect! :D
