### ISSUE TITLE
Other options besides CSS Selector

### ISSUE THREAD

**Issue by gabri25ele** [igorlogius/automate-click#29]
If in a specific page i Don't have CSS Selector, but a direct link (and so I don't know what to put in the selector field) in a specific domain or a specific phrase (click here etc etc)...
it would be nice to have other options besides the css selector

**Comment by igorlogius** [comment]
I hat no plan to add support for a different selection mechanic, 
but if you can share some html source i can try to help you finding a working selector. 

CSS is pretty powerful, and the situation where a CSS selector can not be used should be relatively rare. 

refs.
-  https://www.w3schools.com/cssref/css_selectors.asp
-  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

**Comment by gabri25ele** [comment]
for example in a page like this
https://www.fcportables.com/macrorit-disk-scanner-portable/?xurl=mlxQmVO8qPEmLqCQ219VjxZVRJW9%2FFOnOznxHcxIkjVt26sUSBbekD5NfEpYbGD%2F

![click](https://user-images.githubusercontent.com/33927879/196735994-f75bf7c4-4af0-4871-9afd-fca77b0b3fb3.png)
 
can make a click automatically on the "Click Here to continue... "?
I tried to use "#cntdwn > a:nth-child(1)" but not work in the addon.

**Comment by igorlogius** [comment]
This seems to work fine for me

```
[
    {
        "enabled": true,
        "group": "",
        "annotation": "",
        "tags": "",
        "cssselector": "#cntdwn > a:nth-child(1)",
        "initaldelay": 20000,
        "repeatdelay": 0,
        "maxrepeats": 0,
        "randomrepeatvariance": 0,
        "urlregex": "^https:\\/\\/www\\.fcportables\\.com\\/macrorit-disk-scanner-portable\\/\\?xurl=.*",
        "xclickpos": 0,
        "yclickpos": 0,
        "idx": 0
    }
]
```

**Comment by gabri25ele** [comment]
Ok, now work, "#cntdwn > a:nth-child(1)"
where was I wrong? 
probably in the delay, the only different thing I seem to see.
the automatic click has to wait for the timer, I suppose
otherwise click the first time when there is still nothing
