### ISSUE TITLE
No toolbar icon/button

### ISSUE THREAD

**Issue by Adams3232** [igorlogius/automate-click#45]
Hi,

I don't see the icon after installing the add-on. In add-ons it is installed and enabled.

MacOs 11.7.7
Firefox 115.0.3

**Comment by igorlogius** [comment]
1. Click on the extension button (puzzle piece)
2. In the dropdown popup find the addon entry and right click on it
3. In the context menu that opens, click on `Pin to Toolbar`

![snip_20230731-191044](https://github.com/igorlogius/automate-click/assets/67047467/3a4b20cd-5341-4723-ab6e-6e7824550804)


ref. https://support.mozilla.org/en-US/kb/extensions-button#w_manage-pinned-extensions
