### ISSUE TITLE
want to click login button 

### ISSUE THREAD

**Issue by sundhar517** [igorlogius/automate-click#7]
hi , i have one website in that i want to click login button automatically , 

website : 
https://www.greenpowerpalace.com/login.php

**Comment by igorlogius** [comment]
I'll try to help.

**Comment by igorlogius** [comment]
CSS Selector:  `.login100-form-btn`
URL Regex: `^https:\/\/www\.greenpowerpalace\.com\/login\.php`

If the `Email` and `Password` fields are autofilled then the login should work.
Hope it help.

**Comment by sundhar517** [comment]
Thankyou so much its working

**Comment by igorlogius** [comment]
@sundhar517 

No problem. 
Have a nice day.
